### PR TITLE
Organize dev and non-dev dependencies.

### PR DESCRIPTION
**Pull request by blainesch**
For smaller bundles.

### CODE REVIEW

**Comment by itsthatguy** [comment]
This would be ideal. The problem is, this wont deploy to our production server.

**Comment by blainesch** [comment]
Is there anything I can do to help?

**Comment by itsthatguy** [comment]
@blainesch Let me try to elaborate.

We deploy the avatars-api to heroku. Since we don't track compiled assets, in git, we need heroku to run the build, to generate the compiled assets used on the server. Right now, that means we have to have development assets in the dependencies section. We would need to do a number of things, to be able to separate the two:

1. Remove any reference to static assets in the build tools (`Gulpfile.js`). 
- Rewrite avatars-api in something that doesn't use pre-compilation (ie; get rid of coffeescript, and switch to something like [babel-node](https://babeljs.io/docs/usage/cli/) to handle running the server), or run coffee directly from CLI
- Remove all bower dependencies

I believe that's it, but I might be missing a few things. There's an existing issue that discusses some of this: https://github.com/itsthatguy/generator-spire/issues/19

I hope that helps clarify things.

**Comment by blainesch** [comment]
Makes sense, thanks for clarifying [:

**Pull request closed without merging**
